//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by KLITE.RC
//
#define IDS_HOST                        1
#define IDS_PORT                        2
#define IDS_COMMAND                     3
#define IDS_VERSION                     4
#define IDS_ERR_AUTH_SERVER             5
#define IDS_ERR_GET_CRED                6
#define IDS_ERR_NETID                   7
#define IDS_ERR_NOT_IMPLEMENTED         8

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         101
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
