/*
 *----------------------------------------------------------------
 *
 *  $Source: /users/dev/CVS/Plug-ins/Kerberos/CommonKClient/win32_kclient/krb/MITCPYRT.H,v $
 *  $Revision: 1.1.1.1 $
 *  $Date: 2000/03/25 00:18:31 $
 *  $State: Exp $
 *  $Author: daboo $ Max E. Metral
 *  $Locker:  $
 *
 *  $Log: MITCPYRT.H,v $
 *  Revision 1.1.1.1  2000/03/25 00:18:31  daboo
 *  First Imported.
 *
 * Revision 2.1  1993/06/17  03:33:35  pbh
 * Unknown changes.
 *
 * Revision 2.0  93/05/12  10:44:00  pbh
 * beta 0.13 check in
 * MEWEL support added
 * 
 * 
 * Revision 0.2  92/06/26  12:12:49  pbh
 * alpha 0.1a
 * 
 * Revision 0.1  92/05/21  14:29:01  pbh
 * Initial check in, working pre alpha, 
 * pbh's first pass at memetral's code
 * 
 *
 *
 *
 *----------------------------------------------------------------
 */
#ifndef MIT_COPYRIGHT
#define MIT_COPYRIGHT
/*
 * @doc
 * @module mitcpyrt.h | 
 * This software is being provided to you, the LICENSEE, by the 
 * Massachusetts Institute of Technology (M.I.T.) under the following 
 * license.  By obtaining, using and/or copying this software, you agree 
 * that you have read, understood, and will comply with these terms and 
 * conditions:  
 * 
 * Permission to use, copy, modify and distribute this software and its 
 * documentation for any purpose and without fee or royalty is hereby 
 * granted, provided that you agree to comply with the following copyright 
 * notice and statements, including the disclaimer, and that the same 
 * appear on ALL copies of the software and documentation, including 
 * modifications that you make for internal use or for distribution:
 * 
 * Copyright 1992, 93, 94, 95, 96, 97 by the Massachusetts Institute of Technology.  All rights
 * reserved.  
 * 
 * THIS SOFTWARE IS PROVIDED "AS IS", AND M.I.T. MAKES NO REPRESENTATIONS 
 * OR WARRANTIES, EXPRESS OR IMPLIED.  By way of example, but not 
 * limitation, M.I.T. MAKES NO REPRESENTATIONS OR WARRANTIES OF 
 * MERCHANTABILITY OR FITNESS FOR ANY PARTICULAR PURPOSE OR THAT THE USE OF 
 * THE LICENSED SOFTWARE OR DOCUMENTATION WILL NOT INFRINGE ANY THIRD PARTY 
 * PATENTS, COPYRIGHTS, TRADEMARKS OR OTHER RIGHTS.   
 * 
 * The name of the Massachusetts Institute of Technology or M.I.T. may NOT 
 * be used in advertising or publicity pertaining to distribution of the 
 * software.  Title to copyright in this software and any associated 
 * documentation shall at all times remain with M.I.T., and USER agrees to 
 * preserve same.
 */
#endif /*MIT_COPYRIGHT*/
