//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by KCLIENT.RC
//
#define IDS_PASSNOTCONFIRMED            1
#define _APS_NO_MFC                     1
#define _APS_3D_CONTROLS                1
#define IDS_PASSNOMATCH                 2
#define IDS_PASSTOOSHORT                3
#define IDS_PASSNODIGIT                 4
#define IDS_PASSNOTCHANGED              5
#define IDS_PASSNOLETTER                6
#define IDS_PASSDOMAIN                  7
#define IDS_FORCE_UCREALM				8
#define IDR_MENU1                       101
#define IDM_LSH_KINIT                   102
#define IDD_ENTERPASS                   102
#define IDM_CANCEL_BLOCKING             103
#define IDD_CHANGEPASS                  103
#define IDM_DEST_TKTS                   104
#define IDI_DOGGIE                      104
#define IDI_BROKENKEY                   107
#define IDM_TIMESYNC                    115
#define IDC_EDIT2                       1001
#define IDD_TEXT1                       1002
#define IDC_EDIT1                       1003
#define IDC_REALM_CHECK                 1004
#define KADM_ERR_RESOURCE_BASE          3000
#define LSH_ERR_RESOURCE_BASE           3300
#define TABLE_NAME_BASE                 3600
#define IDS_UNKNOWN                     3604
#define IDS_SAYERROR                    3605
#define IDS_NOMESSAGE                   3606
#define KRB_ERR_RESOURCE_BASE           4000
#define COM_ERR_RESOURCE_BASE           10000
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        107
#define _APS_NEXT_COMMAND_VALUE         105
#define _APS_NEXT_CONTROL_VALUE         1005
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
